### PR TITLE
Custom field consolidation

### PR DESCRIPTION
**Pull request by s-zimm**

### CODE REVIEW

**Review by pmamut — CHANGES_REQUESTED** [review]
see commentary on https://github.com/versionone/scripts/pull/24

**Comment by s-zimm** [comment]
Does changing the base table (CustomText instead of AssetAudit) let us not worry about history gaps? We figured just pulling the rows from the Custom Field table and executing based on those rows would accomplish what we needed (still giving us the proper AuditBegin/AuditEnd's that we would need for re-stitching).

Also, doesn't this check ensure we're only getting rows with the proper Definition throughout the script?
https://github.com/versionone/scripts/pull/27/files#diff-425589328cfd3c371d22346a22377a82303077126ed5096537fe57d16c63bdfdR32

**Comment by pmamut** [comment]
>Does changing the base table (CustomText instead of AssetAudit) let us not worry about history gaps? 
Unfortunately, it doesn't - and by using it you also lose the "no other changes in-between two custom filed updates" condition that was enforced by keying off of sequential `AssetAudit` rows.

>Also, doesn't this check ensure we're only getting rows with the proper Definition throughout the script?
It does not. `Definition` is a part of the `CustomXXX` primary key, and must be referenced when matching up rows - otherwise you end up matching together rows from different custom attributes that just happen to have the same `AuditBegin`.

**Comment by pmamut** [comment]
As I was looking over and massaging current iteration of this script, I came to realization that even in its present form it is still deeply flawed.

We failed to realize that the sparse nature of of custom tables serves to efficiently represent _lack of a value_ - i.e. what would've been a `null` value in a regular asset history table - and the consolidation script needs to take these "virtual" `null` values into account, both when dropping extraneous updates, and when restitching remaining history.

Let's start fresh - I will pair on it with you.

**Pull request closed without merging**
