### PR TITLE
D-17750 fixing wrong row updating.

### PR DESCRIPTION
**Pull request by lremedi**

### CODE REVIEW

**Review by pmamut — CHANGES_REQUESTED** [review]
```
create table #suspect(ID int not null, CurrentAuditID int null, NextAuditId int null)
create table #bad(ID int not null, CurrentAuditID int null, NextAuditId int null)
```
* `NextAuditId` case matters. Please test on a DB with _case-sensitive_ collation.
* `CurrentAuditID` and `NextAuditId` must both be `not null`, since both rows must exist for a change to be "suspect".

```
	from dbo.AssetAudit AA
	join [Audit] A ON A.ID = AA.AuditID
	join dbo.BaseAsset bA on bA.ID=AA.ID and bA.AssetType=AA.AssetType and bA.AuditBegin=AA.AuditID
```
* `Audit` must be schema-qualified.
* there will not be a `dbo.BaseAsset` row for every `dbo.AssetAudit` one, so `join` effectively drops changes (to other asset tables) that may have occurred between two `BaseAsset` changes. Since `ROW_NUMBER()` in the projection operates on the _final_ result set (and not on `AssetAudit` source), `B.R=A.R+1` would not correctly enforce "without intervening in-between changes to other attributes" safety constraint. You want to build a "suspect" sequence just out of `AssetAudit`, and then enforce all constraints (same user, time interval, change to description without changes to any other attributes) when building "bad".

```
FROM H as A
JOIN H as B on B.ID=A.ID and B.AssetType=A.AssetType and B.R=A.R+1
AND ISNULL(B.[ChangedByID] ,-1) = A.[ChangedByID]  -- Consecutive changes from the same user
```
`Audit.ChangedByID` is nullable (because reasons), so need to null-check `A.[ChangedByID]` as well

```
-- consecutive redundant BaseAsset re-open/close
declare @sql varchar(max); select @sql = '
insert #bad(ID, CurrentAuditID, NextAuditID)
```
no comment is better than lying comment

**Review by pmamut — APPROVED** [review]
Looks good 👍 

I think `insert #baseassets(ID, CurrentAuditID, NextAuditID)` and `insert #suspect(ID, CurrentAuditID, NextAuditID)` sets could be built in a single compbined statement, but what you have now works,

**Comment by lremedi** [comment]
Yeap, I think you are right, but I would like to keep it for readability.

**Comment by pmamut** [comment]
I thought of something else - we really ought to output `ID`, `AssetType`, and `AuditID` (and maybe `ChangedByID` and `ChangeDateUTC`) of the rows we're purging. This would serve as both a reference of stuff about to get whacked during a dry run, and a sanity check for our own sake (like when we expect histories of only 2 stories to get whacked, for example).

**Pull request merged**
